### ISSUE TITLE
Pkg is very popular on Twitter this weekend FYI

### ISSUE THREAD

**Issue by smach** [dgkf/ggpackets#9]
Hi, this isn't an issue, but I just wanted you to know that I discovered this package while browsing on GitHub, it looked very cool so I tweeted about it yesterday. That tweet has more than 700 likes and 100 retweets (including by Hadley) as well as comments saying this is a great idea. I didn’t see that you have an account on Twitter, but you should be able to view the tweet even without an account. Thanks for the package!
https://twitter.com/sharon000/status/1540670132543836160?s=21&t=HSJUMCIfR-XTHrhe6Tli2w

**Comment by dgkf** [comment]
This is so sweet! :blush:

Thanks for letting me know - it made my night. I'm thrilled to hear that people like it. 

I gotta admit it's a bit like seeing a ghost. This was my first ever package, and aside from a few minor updates it's been mostly collecting dust for a few years. When I wrote it, the `tidyverse`'s non-standard evaluation was in quite a bit of flux, with `rlang`/`tidyeval` just entering into the picture with the introduction of the `!!` quasi-quoting. I wasn't totally sure if this work would be compatible.

I'm glad to hear it's been discovered. Given the enthusiasm, I'll try to get this pushed up to CRAN. I'll have to revisit it just to confirm things are still working properly with modern `tidyverse` - please report any bugs you might find! I don't do nearly as much plotting as I used to, so I'm not as equipped to stress test this. 

I'm going to close the issue just for repo cleanliness - the message was very much appreciated

**Comment by dgkf** [comment]
Just a short follow-up. The enthusiasm from the twitter community was the push I needed to tidy up the package and prep it for a release. 

You can find the package now on CRAN. :tada:

**Comment by smach** [comment]
Cool, thanks for letting me know!! I just downloaded the CRAN version. 
People are indeed enthusiastic!

**Comment by smach** [comment]
![0B2DD787-6E78-4DE9-BF9A-92F0E7E12548](https://user-images.githubusercontent.com/3394160/179118664-6215491b-ee26-43ec-b3dd-faaaa7c4f73c.jpeg)

**Comment by smach** [comment]
And one more this morning 😀
![CE8B6DE3-159A-4049-A559-CCD62DF2BE68](https://user-images.githubusercontent.com/3394160/179218208-44e0f707-8f88-4bee-9c1f-253340a247aa.jpeg)
